site_name: Cluster Usage
site_url: https://ltalignani.github.io/mkdocs-cluster-usage/
repo_url: https://github.com/ltalignani/mkdocs-cluster-usage
repo_name: ltalignani/mkdocs-cluster-usage

theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-cnrs.png
  favicon: assets/favicon.ico
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.footer
    - navigation.instant
    - content.code.copy
    - toc.integrate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple
    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  - Home: index.md
  - Logging: Logging.md
  - Transfering Files:
    - Using Rsync: transfer/Rsync.md
    - Using Filezilla (SFTP) : transfer/SFTP.md
  - Submitting Jobs:
    - Batch mode: Submitting_jobs.md
    - Interactive mode: Interactive_jobs.md
  - Monitoring: Monitoring.md
  - Running Clean & Reproducible Jobs:
    - Python: python.md
    - R: R.md
  - About: about.md


markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.blocks.caption
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - md_in_html
  - def_list
  
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ltalignani/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/loic-talignani-83a7581a2/
  consent:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    cookies:
      analytics:
        name: Google Analytics
        checked: false
    actions:
      - accept
      - manage
      - reject

extra_css:
  - css/overrides.css


copyright: >
  Copyright &copy; 2025 Loïc Talignani -
  <a href="#__consent">Change cookie settings</a>