site_name: Cluster Usage
site_url: https://ltalignani.github.io/mkdocs-cluster-usage/
nav:
  - Home: index.md
  - Logging: Logging.md
  - Submitting Jobs:
    - Batch mode: Submitting_jobs.md
    - Interactive mode: Interactive_jobs.md
  - Monitoring: Monitoring.md
  - Running Clean & Reproducible Jobs:
    - Python: python.md
    - R: R.md
  - About: about.md
theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo-cnrs.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.instant
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - navigation.tracking
    - content.code.copy
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: indigo
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      use_pygments: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: "mermaid"
          class: "mermaid"
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

extra_css:
  - css/overrides.css
  - 
copyright: Copyright &copy; 2025 Loïc Talignani